### ISSUE TITLE
precompilation

### ISSUE THREAD

**Issue by hugomrdias** [Rapid-Application-Development-JS/itemplate#2]
for precompilation a compile function like this would need to receive lib and helpers in the inner function

``` js
(function(lib,helpers) {
    return function(data){
        var o=lib.elementOpen,c=lib.elementClose,t=lib.text,v=lib.elementVoid;
        o('div', null, null, 'class', 'box');
            t( data.content );
        c('div');
        helpers['my-console']({data:7+8});}
})

```

something like 

``` js
(function() {
    return function(data, lib, helpers){
        // throw error or something if not lib and helpers
        var o=lib.elementOpen,c=lib.elementClose,t=lib.text,v=lib.elementVoid;
        o('div', null, null, 'class', 'box');
            t( data.content );
        c('div');
        helpers['my-console']({data:7+8});}
})

```

``` js
var template = require('app.tpl');
idom.patch(document.getElementById('app'), function () {
    template(data, idom, helpers);
});
```

and maybe helper functions should be protected so we can render without all helpers functions registered.

i'm just sharing some ideias here, what think about this ? i'm thinking about writing a transform for browserify

**Comment by MobiDevBiz** [comment]
Thank you for your attention.

Unfortunately, we cannot add parameters (`lib`, `helpers`) directly into the rendering function because it is transmitted as a call parameter to the function [path](http://google.github.io/incremental-dom/#api/patch), and for compatibility with the future versions of (incremental-dom)https://github.com/google/incremental-dom] we cannot change the semantics of calling a rendering function. This is why `lib` and `helpers` are transmitted via closure, and not as call parameters.

But we can suggest the following option, if the second parameter is absent during the compilation of the template, which means you won't transmit the link to the library:

``` javascript
var renderFn = itemplate.compile(templateStr[, IncrementalDOM]);
```

In this case it's not a rendering function that will be compiled, it will be just a function without closure and wrapping:

``` javascript
function (data, lib, helpers){
        // throw error or something if not lib and helpers
        var o=lib.elementOpen,c=lib.elementClose,t=lib.text,v=lib.elementVoid;
        o('div', null, null, 'class', 'box');
            t( data.content );
        c('div');
        helpers['my-console']({data:7+8});
}
```

Here it's up to you to decide how to call it and transmit compilation parameters; for example, as you suggested:

``` javascript
idom.patch(document.getElementById('app'), function () {
    template(data, idom, helpers);
});
```

> Thank you for the suggestion. It allows to work with templates with more flexibility; for example, call several templates in one rendering function, or introduce additional logic, such as filtration.

**Comment by MobiDevBiz** [comment]
done $-)
